# Generated by Django 3.0.2 on 2020-02-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketting', '0002_marketingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='update',
            new_name='updated',
        ),
    ]
