# Generated by Django 3.0.2 on 2020-02-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingprofile_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='customer_id',
        ),
    ]
