# Generated by Django 3.0.2 on 2020-01-29 10:05

from django.db import migrations, models
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200128_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image/no_image.jpg', null=True, upload_to=product.utils.upload_image_path),
        ),
    ]
