# Generated by Django 3.0.2 on 2020-01-30 15:41

from django.db import migrations, models
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200129_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/no_image.jpg', null=True, upload_to=product.utils.upload_image_path),
        ),
    ]
