# Generated by Django 3.0.2 on 2020-01-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_discound_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discound_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19),
        ),
    ]
