# Generated by Django 3.0.2 on 2020-01-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200131_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discound_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
