# Generated by Django 3.0.2 on 2020-02-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='fname',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='lname',
        ),
    ]
