# Generated by Django 3.0.2 on 2020-02-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestModel',
            new_name='GuestEmail',
        ),
    ]
